spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: your_mailtrap_user
    password: your_mailtrap_pass
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers

spring.jpa.open-in-view: false
server:
  port: 8080
