spring:
  datasource:
    # for db2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #      for postgres
  #    url: jdbc:postgresql://localhost:5432/lms_db
  #    username: lms_user
  #    password:
  #    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      # for db2
#      ddl-auto: none
      ddl-auto: update
    #      for postgres
    #      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 13aa81e48ff568
    password: a82e0758f7037f
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers

spring.jpa.open-in-view: false
server:
  port: 8080

app:
  email-executor:
    core-pool-size: 5
    max-pool-size: 20
    queue-capacity: 50
    thread-name-prefix: "email-executor-"
